"""Add password_hash to UserDB model

Revision ID: 3933f097eb44
Revises: 47ff6fd87144
Create Date: 2023-12-08 22:00:28.217077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3933f097eb44'
down_revision = '47ff6fd87144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_db', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
