"""Added to news model author field

Revision ID: 9a7e6eb99c6b
Revises: 47339a485516
Create Date: 2023-12-10 21:30:05.683397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7e6eb99c6b'
down_revision = '47339a485516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=70), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
