"""reactions deleted

Revision ID: e73f298eecd4
Revises: fd3d4a9cdfe0
Create Date: 2023-12-16 17:55:37.910835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e73f298eecd4'
down_revision = 'fd3d4a9cdfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('reactions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reactions', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))

    # ### end Alembic commands ###
