"""reations list added

Revision ID: fd3d4a9cdfe0
Revises: b48a85ad2fc2
Create Date: 2023-12-14 18:11:13.073259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3d4a9cdfe0'
down_revision = 'b48a85ad2fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reactions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('reactions')

    # ### end Alembic commands ###
